[workspace]
channels = ["conda-forge"]
name = "pytorch"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
pandas = "*"
openpyxl = ">=3.1.5,<4"
polars = ">=1.35.1,<2"
umap-learn = ">=0.5.9.post2,<0.6"
pacmap = ">=0.8.0,<0.9"
catboost = ">=1.2.8,<2"
optuna-integration = ">=4.6.0,<5"
xgboost = ">=3.1.1,<4"
lightgbm = ">=4.6.0,<5"

[pypi-dependencies]
pytorch-lightning = "*"
scikit-learn = "*"
pyclustering = "*"
biopython = "*"
optuna = "*"
ipykernel = "*"
pynvim = "*"
fastexcel = ">=0.18.0, <0.19"
