[workspace]
authors = ["RafailTn <rafailadam46@gmail.com>"]
channels = ["conda-forge"]
name = "gluon"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = '3.10.*'
polars = '*'

[pypi-dependencies]
autogluon = { version = ">=1.4.0, <2", extras = ["tabarena"] }
pandas = ">=2.3.3, <3"
fastexcel = ">=0.18.0, <0.19"
ipykernel = ">=7.1.0, <8"
pynvim = ">=0.6.0, <0.7"
openpyxl = ">=3.1.5, <4"

