[workspace]
authors = ["Rafail <rafailadam46@gmail.com>"]
channels = ["conda-forge"]
name = "ag"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
autogluon = ">=1.4.0,<2"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
ipykernel = ">=6.30.1, <7"
pynvim = ">=0.5.2, <0.6"
pyclustering = '*'
