[workspace]
channels = ["conda-forge"]
name = "agents"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12, <3.13"
polars = ">=1.37.1,<2"
cellxgene-census = ">=1.17.0,<2"

[pypi-dependencies]
langchain-chroma = "*"
torch = "*"
langgraph = "*"
langchain = "*"
langchain-ollama = "*"
langgraph-cli = "*"
ipykernel = "*"
langchain-tavily = "*"
langchain-core = "*"
trustcall = "*"
langchain-community = "*"
biopython = "*"
langgraph-sdk = "*"
langgraph-prebuilt = "*"
pynvim = "*"
langsmith = "*"
dspy = "*"
langgraph-supervisor = "*"
langgraph-swarm = "*"
agentevals = "*"
langchain-mcp-adapters = "*"
langmem = "*"
langchain-experimental = "*"
langchain-huggingface = "*"
langchain-classic = ">=1.0.0, <2"
sentence-transformers = ">=5.1.2, <6"
rank-bm25 = ">=0.2.2, <0.3"
gradio = ">=6.2.0, <7"
kuzu = ">=0.11.3, <0.12"
gliner = ">=0.2.24, <0.3"
huggingface-hub = { version = ">=0.36.0, <0.37", extras = ["cli"] }
pymupdf = ">=1.26.7, <2"
pypdf = ">=6.6.2, <7"
alphagenome = ">=0.5.1, <0.6"
atlasapprox = ">=0.2.4, <0.3"
