[workspace]
channels = ["conda-forge"]
name = "causal"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
polars = ">=1.35.1,<2"

[pypi-dependencies]
pywhy = "*"
econml = "*"
causal-learn = "*"
catenets = "*"
gcastle = "*"
ipykernel = "*"
pynvim = "*"
fastexcel = ">=0.18.0, <0.19"
