[workspace]
channels = ["conda-forge"]
name = "atom"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
polars = ">=1.35.1,<2"

[pypi-dependencies]
pmdarima='==2.0.4'
sktime='==0.36.1' 
skpro='==2.9.0'
scikit-learn='==1.6.1'
category_encoders='==2.8.1' 
imbalanced-learn="*" 
optuna=">=4.6.0, <5" 
shap='==0.47.1' 
numpy='==1.26.4'
pandas="*"
scipy="*"
matplotlib="*" 
seaborn="*"
xgboost="*" 
lightgbm='==4.6.0'
atom-ml = ">=6.1.0, <7"
catboost = ">=1.2.8, <2"
optuna-integration = ">=4.6.0, <5"
fastexcel = ">=0.18.0, <0.19"
ipykernel = ">=7.1.0, <8"
pynvim = ">=0.6.0, <0.7"
openpyxl = ">=3.1.5, <4"
